---
  - name: Run the module my_own_module
    my_own_module:
      name: "{{ p_name }}"
      path: "{{ p_path }}"
      content: "{{ p_content }}"
      force: false
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'